blank_issues_enabled: false
contact_links:
  - name: Contributor Guide (AGENTS.md)
    url: https://github.com/dariuszparys/try-rs/blob/main/AGENTS.md
    about: Project structure, commands, style, and PR requirements.
