name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Cargo build
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check --locked

      - name: Cargo test
        run: cargo test --all --locked

      - name: Rustfmt (check)
        run: cargo fmt --all -- --check

      - name: Clippy (lint)
        run: cargo clippy --all-targets -- -D warnings
